require('dotenv').config();
const sequelize = require('./config/database');
const {
  Worker,
  WorkerPermission,
  User,
  ConnectorDefinition,
  WorkforceBundle,
  WorkforceBundleMember,
} = require('./models');
const bcrypt = require('bcrypt');

const developerId = '11111111-1111-1111-1111-111111111111';

const digitalEmployees = [
  {
    id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    name: 'Naomi Carter',
    role_title: 'Customer Support Specialist',
    department: 'Customer Experience',
    career_level: 'Professional',
    equivalent_experience_years: 5,
    skills: ['Inbox ownership', 'Escalation handling', 'Knowledge support'],
    work_modes: ['support', 'coverage', 'role_fill'],
    human_oversight: 'Reports to the customer-assigned human manager and escalates sensitive decisions.',
    support_summary: 'Supports customer-facing teams, covers service gaps, and can fill a defined support role.',
    regular_salary_annual: 66000,
    avatar_variant: 1,
    developer_name: 'ORCA Studios',
    readiness_state: 'deployable',
    developer_id: developerId,
    description: 'Handles customer conversations, support tickets, service recovery, and escalations 24/7/365.',
    category: 'support',
    icon_url: null,
    hero_banner_url: null,
    avg_rating: 0,
    total_reviews: 0,
    total_deployments: 0,
    price_model: 'subscription',
    base_price: 1925.00,
    stripe_price_id: process.env.STRIPE_PRICE_CUSTOMER_SUPPORT || null,
    version: '1.0.0',
    release_notes: 'Named professional profile and governed workspace-agnostic release.',
    status: 'published',
  },
  {
    id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    name: 'Sofia Hayes',
    role_title: 'Founder and Executive Assistant',
    department: 'Operations and Administration',
    career_level: 'Professional',
    equivalent_experience_years: 8,
    skills: ['Scheduling', 'Research briefs', 'Executive follow-up'],
    work_modes: ['support', 'coverage', 'role_fill'],
    human_oversight: 'Works under the executive or operations leader who owns final decisions and approvals.',
    support_summary: 'Reduces administrative friction and expands executive capacity without removing human authority.',
    regular_salary_annual: 72000,
    avatar_variant: 2,
    developer_name: 'ORCA Studios',
    readiness_state: 'deployable',
    developer_id: developerId,
    description: 'Manages email, calendars, files, follow-ups, and administrative workflows 24/7/365.',
    category: 'admin',
    icon_url: null,
    hero_banner_url: null,
    avg_rating: 0,
    total_reviews: 0,
    total_deployments: 0,
    price_model: 'subscription',
    base_price: 2100.00,
    stripe_price_id: process.env.STRIPE_PRICE_FOUNDER_ASSISTANT || null,
    version: '1.0.0',
    release_notes: 'Named professional profile and governed workspace-agnostic release.',
    status: 'published',
  },
  {
    id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    name: 'Aisha Bennett',
    role_title: 'Commerce Support Specialist',
    department: 'Customer Experience',
    career_level: 'Professional',
    equivalent_experience_years: 6,
    skills: ['Order support', 'Customer recovery', 'Product coordination'],
    work_modes: ['support', 'coverage', 'role_fill'],
    human_oversight: 'Escalates refunds, destructive actions, and policy exceptions to the assigned human manager.',
    support_summary: 'Supports commerce teams, covers high-volume periods, and fills defined service operations gaps.',
    regular_salary_annual: 72000,
    avatar_variant: 3,
    developer_name: 'ORCA Studios',
    readiness_state: 'deployable',
    developer_id: developerId,
    description: 'Supports orders, customers, products, fulfillment questions, and service recovery 24/7/365.',
    category: 'support',
    icon_url: null,
    hero_banner_url: null,
    avg_rating: 0,
    total_reviews: 0,
    total_deployments: 0,
    price_model: 'subscription',
    base_price: 2100.00,
    stripe_price_id: process.env.STRIPE_PRICE_COMMERCE_SUPPORT || null,
    version: '1.0.0',
    release_notes: 'Named professional profile and governed workspace-agnostic release.',
    status: 'published',
  },
  {
    id: 'dddddddd-dddd-dddd-dddd-dddddddddddd',
    name: 'Andre Lewis',
    role_title: 'Sales Follow-Up Specialist',
    department: 'Sales and Revenue',
    career_level: 'Professional',
    equivalent_experience_years: 6,
    skills: ['CRM updates', 'Lead follow-up', 'Opportunity tracking'],
    work_modes: ['support', 'coverage', 'role_fill'],
    human_oversight: 'Works from approved sales policies and escalates pricing, commitments, and exceptions.',
    support_summary: 'Supports the sales team, prevents follow-up gaps, and can cover a defined pipeline role.',
    regular_salary_annual: 100000,
    avatar_variant: 4,
    developer_name: 'ORCA Studios',
    readiness_state: 'deployable',
    developer_id: developerId,
    description: 'Follows up with leads, updates records, nurtures opportunities, and books meetings 24/7/365.',
    category: 'sales',
    icon_url: null,
    hero_banner_url: null,
    avg_rating: 0,
    total_reviews: 0,
    total_deployments: 0,
    price_model: 'subscription',
    base_price: 2917.00,
    stripe_price_id: process.env.STRIPE_PRICE_SALES_FOLLOW_UP || null,
    version: '1.0.0',
    release_notes: 'Named professional profile and governed workspace-agnostic release.',
    status: 'published',
  },
  {
    id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
    name: 'Maya Bennett',
    role_title: 'Content Production Specialist',
    department: 'Marketing and Creative',
    career_level: 'Professional',
    equivalent_experience_years: 7,
    skills: ['Research', 'Drafting', 'Publishing workflows'],
    work_modes: ['support', 'coverage', 'role_fill'],
    human_oversight: 'Works from approved brand and publishing rules; external publication requires configured approval.',
    support_summary: 'Supports human creative teams, covers production gaps, and can fill a defined content operations role.',
    regular_salary_annual: 84000,
    avatar_variant: 5,
    developer_name: 'ORCA Studios',
    readiness_state: 'deployable',
    developer_id: developerId,
    description: 'Researches, drafts, organizes, and publishes approved content workflows 24/7/365.',
    category: 'design',
    icon_url: null,
    hero_banner_url: null,
    avg_rating: 0,
    total_reviews: 0,
    total_deployments: 0,
    price_model: 'subscription',
    base_price: 2450.00,
    stripe_price_id: process.env.STRIPE_PRICE_CONTENT_PRODUCTION || null,
    version: '1.0.0',
    release_notes: 'Named professional profile and governed workspace-agnostic release.',
    status: 'published',
  },
];

const permissions = [
  ['aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'messages.read', 'Read customer messages', 'Read incoming customer conversations.', 'message', 'read', 'medium', true, false],
  ['aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'messages.send', 'Send customer replies', 'Send replies within customer-approved resources.', 'message', 'create', 'high', true, false],
  ['aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'tickets.update', 'Update support tickets', 'Update ticket status and internal support notes.', 'ticket', 'update', 'high', false, false],
  ['bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'email.read', 'Read approved mailboxes', 'Read messages in customer-selected mailboxes.', 'email', 'read', 'medium', true, false],
  ['bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'email.send', 'Send approved email', 'Send email from customer-approved accounts.', 'email', 'create', 'high', true, false],
  ['bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'calendar.events.create', 'Create calendar events', 'Create meetings on customer-approved calendars.', 'calendar_event', 'create', 'high', false, false],
  ['bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'files.read', 'Read approved files', 'Read files from customer-selected resources.', 'file', 'read', 'medium', false, false],
  ['cccccccc-cccc-cccc-cccc-cccccccccccc', 'orders.read', 'Read orders', 'Read customer-approved order records.', 'order', 'read', 'medium', true, false],
  ['cccccccc-cccc-cccc-cccc-cccccccccccc', 'customers.read', 'Read customer records', 'Read customer records needed to resolve service requests.', 'customer', 'read', 'medium', true, false],
  ['cccccccc-cccc-cccc-cccc-cccccccccccc', 'orders.update', 'Update orders', 'Update approved order fields and fulfillment notes.', 'order', 'update', 'critical', false, true],
  ['dddddddd-dddd-dddd-dddd-dddddddddddd', 'contacts.read', 'Read contacts', 'Read customer-approved contact records.', 'contact', 'read', 'medium', true, false],
  ['dddddddd-dddd-dddd-dddd-dddddddddddd', 'contacts.update', 'Update contacts', 'Update follow-up status and approved contact fields.', 'contact', 'update', 'high', true, false],
  ['dddddddd-dddd-dddd-dddd-dddddddddddd', 'calendar.events.create', 'Book meetings', 'Create approved sales meetings.', 'calendar_event', 'create', 'high', false, false],
  ['eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 'files.read', 'Read source material', 'Read customer-selected research and source files.', 'file', 'read', 'medium', true, false],
  ['eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 'documents.create', 'Create content documents', 'Create drafts in customer-approved document systems.', 'document', 'create', 'high', true, false],
  ['eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 'content.publish', 'Publish approved content', 'Publish content only after customer-defined approval checks.', 'content', 'create', 'critical', false, true],
].map(([worker_id, capability_key, name, description, resource_type, action, risk_level, is_required, requires_human_approval]) => ({
  worker_id,
  capability_key,
  name,
  description,
  resource_type,
  action,
  risk_level,
  is_required,
  requires_human_approval,
  constraints_schema: {},
}));

const connectorDefinitions = [
  {
    key: 'generic-rest',
    name: 'Generic REST API',
    description: 'Connects ORCA to a real HTTPS API using customer-defined operations and capabilities.',
    category: 'universal',
    auth_type: 'custom',
    adapter_key: 'generic-rest',
    status: 'active',
    is_native: false,
    supports_workspace_discovery: false,
    supports_resource_discovery: true,
    supports_token_refresh: false,
    capability_manifest: { schema_version: '1.0', capabilities: [{ key: 'api.request' }] },
    configuration_schema: {},
  },
  {
    key: 'generic-webhook',
    name: 'Signed Webhook',
    description: 'Installs and controls a digital employee through a real signed webhook endpoint.',
    category: 'universal',
    auth_type: 'webhook',
    adapter_key: 'generic-webhook',
    status: 'active',
    is_native: false,
    supports_workspace_discovery: false,
    supports_resource_discovery: false,
    supports_token_refresh: false,
    capability_manifest: { schema_version: '1.0', capabilities: [{ key: 'webhook.deliver' }] },
    configuration_schema: {},
  },
  { key: 'slack', name: 'Slack', description: 'Native Slack workspace integration.', category: 'messaging', auth_type: 'oauth2', adapter_key: 'slack', status: 'not_configured', is_native: true, supports_workspace_discovery: true, supports_resource_discovery: true, supports_token_refresh: false, capability_manifest: { schema_version: '1.0', capabilities: [{ key: 'messages.read' }, { key: 'messages.send' }, { key: 'files.read' }] }, configuration_schema: {} },
  { key: 'google-workspace', name: 'Google Workspace', description: 'Native Gmail, Calendar, Drive, and Contacts integration.', category: 'productivity', auth_type: 'oauth2', adapter_key: 'google-workspace', status: 'not_configured', is_native: true, supports_workspace_discovery: true, supports_resource_discovery: true, supports_token_refresh: true, capability_manifest: { schema_version: '1.0', capabilities: [{ key: 'email.read' }, { key: 'email.send' }, { key: 'calendar.events.create' }, { key: 'files.read' }, { key: 'documents.create' }, { key: 'contacts.read' }, { key: 'contacts.update' }] }, configuration_schema: {} },
  { key: 'microsoft-365', name: 'Microsoft 365', description: 'Native Outlook, Teams, OneDrive, SharePoint, Calendar, and Contacts integration.', category: 'productivity', auth_type: 'oauth2', adapter_key: 'microsoft-365', status: 'not_configured', is_native: true, supports_workspace_discovery: true, supports_resource_discovery: true, supports_token_refresh: true, capability_manifest: { schema_version: '1.0', capabilities: [{ key: 'messages.read' }, { key: 'messages.send' }, { key: 'email.read' }, { key: 'email.send' }, { key: 'calendar.events.create' }, { key: 'files.read' }, { key: 'documents.create' }, { key: 'contacts.read' }, { key: 'contacts.update' }] }, configuration_schema: {} },
  { key: 'shopify', name: 'Shopify', description: 'Native Shopify store integration.', category: 'commerce', auth_type: 'oauth2', adapter_key: 'shopify', status: 'not_configured', is_native: true, supports_workspace_discovery: true, supports_resource_discovery: true, supports_token_refresh: false, capability_manifest: { schema_version: '1.0', capabilities: [{ key: 'orders.read' }, { key: 'orders.update' }, { key: 'customers.read' }, { key: 'products.read' }, { key: 'products.update' }] }, configuration_schema: {} },
  { key: 'hubspot', name: 'HubSpot', description: 'Native HubSpot CRM integration.', category: 'crm', auth_type: 'oauth2', adapter_key: 'hubspot', status: 'not_configured', is_native: true, supports_workspace_discovery: true, supports_resource_discovery: true, supports_token_refresh: true, capability_manifest: { schema_version: '1.0', capabilities: [{ key: 'contacts.read' }, { key: 'contacts.update' }, { key: 'tickets.update' }, { key: 'customers.read' }] }, configuration_schema: {} },
  { key: 'notion', name: 'Notion', description: 'Native Notion workspace integration.', category: 'knowledge', auth_type: 'oauth2', adapter_key: 'notion', status: 'not_configured', is_native: true, supports_workspace_discovery: true, supports_resource_discovery: true, supports_token_refresh: false, capability_manifest: { schema_version: '1.0', capabilities: [{ key: 'files.read' }, { key: 'documents.create' }, { key: 'documents.update' }] }, configuration_schema: {} },
];

const bundles = [
  { id: '10000000-0000-0000-0000-000000000001', slug: 'customer-experience-team', name: 'Customer Experience Team', bundle_type: 'team', department: 'Customer Experience', description: 'A coordinated support team for customer conversations, order questions, coverage, and service recovery under one human manager.', status: 'published', human_authority_required: true, launch_rate_percent: 35, version: '1.0.0' },
  { id: '10000000-0000-0000-0000-000000000002', slug: 'revenue-growth-team', name: 'Revenue Growth Team', bundle_type: 'team', department: 'Sales and Revenue', description: 'A coordinated team for lead follow-up, executive coordination, and content support under customer-defined authority.', status: 'published', human_authority_required: true, launch_rate_percent: 35, version: '1.0.0' },
  { id: '10000000-0000-0000-0000-000000000003', slug: 'business-operations-team', name: 'Business Operations Team', bundle_type: 'team', department: 'Operations and Administration', description: 'A support team for administration, customer coordination, and content operations that helps human staff keep work moving.', status: 'published', human_authority_required: true, launch_rate_percent: 35, version: '1.0.0' },
  { id: '20000000-0000-0000-0000-000000000001', slug: 'customer-experience-department', name: 'Customer Experience Department', bundle_type: 'department', department: 'Customer Experience', description: 'A governed department plan combining frontline support, commerce support, and administrative coordination.', status: 'published', human_authority_required: true, launch_rate_percent: 35, version: '1.0.0' },
  { id: '20000000-0000-0000-0000-000000000002', slug: 'revenue-growth-department', name: 'Revenue and Growth Department', bundle_type: 'department', department: 'Sales and Revenue', description: 'A governed department plan combining sales follow-up, content production, and executive coordination.', status: 'published', human_authority_required: true, launch_rate_percent: 35, version: '1.0.0' },
  { id: '20000000-0000-0000-0000-000000000003', slug: 'operations-administration-department', name: 'Operations and Administration Department', bundle_type: 'department', department: 'Operations and Administration', description: 'A governed department plan that supports executives, customers, and recurring business operations.', status: 'published', human_authority_required: true, launch_rate_percent: 35, version: '1.0.0' },
];

const bundleMembers = [
  ['30000000-0000-0000-0000-000000000001', bundles[0].id, digitalEmployees[0].id, 1, 'Customer support lead'],
  ['30000000-0000-0000-0000-000000000002', bundles[0].id, digitalEmployees[2].id, 2, 'Commerce support'],
  ['30000000-0000-0000-0000-000000000003', bundles[0].id, digitalEmployees[1].id, 3, 'Operations coordination'],
  ['30000000-0000-0000-0000-000000000004', bundles[1].id, digitalEmployees[3].id, 1, 'Sales follow-up'],
  ['30000000-0000-0000-0000-000000000005', bundles[1].id, digitalEmployees[4].id, 2, 'Content production'],
  ['30000000-0000-0000-0000-000000000006', bundles[1].id, digitalEmployees[1].id, 3, 'Executive coordination'],
  ['30000000-0000-0000-0000-000000000007', bundles[2].id, digitalEmployees[1].id, 1, 'Executive operations'],
  ['30000000-0000-0000-0000-000000000008', bundles[2].id, digitalEmployees[0].id, 2, 'Customer coordination'],
  ['30000000-0000-0000-0000-000000000009', bundles[2].id, digitalEmployees[4].id, 3, 'Content operations'],
  ['30000000-0000-0000-0000-000000000010', bundles[3].id, digitalEmployees[0].id, 1, 'Customer support'],
  ['30000000-0000-0000-0000-000000000011', bundles[3].id, digitalEmployees[2].id, 2, 'Commerce support'],
  ['30000000-0000-0000-0000-000000000012', bundles[3].id, digitalEmployees[1].id, 3, 'Department coordination'],
  ['30000000-0000-0000-0000-000000000013', bundles[4].id, digitalEmployees[3].id, 1, 'Sales operations'],
  ['30000000-0000-0000-0000-000000000014', bundles[4].id, digitalEmployees[4].id, 2, 'Marketing production'],
  ['30000000-0000-0000-0000-000000000015', bundles[4].id, digitalEmployees[1].id, 3, 'Department coordination'],
  ['30000000-0000-0000-0000-000000000016', bundles[5].id, digitalEmployees[1].id, 1, 'Executive operations'],
  ['30000000-0000-0000-0000-000000000017', bundles[5].id, digitalEmployees[0].id, 2, 'Customer coordination'],
  ['30000000-0000-0000-0000-000000000018', bundles[5].id, digitalEmployees[4].id, 3, 'Content administration'],
].map(([id, workforce_bundle_id, worker_id, position, role_label]) => ({ id, workforce_bundle_id, worker_id, position, role_label }));

async function seed() {
  await sequelize.sync();

  const seedPassword = process.env.SEED_ADMIN_PASSWORD;
  if (seedPassword) {
    const password = await bcrypt.hash(seedPassword, 12);
    await User.upsert({
      id: developerId,
      email: process.env.SEED_ADMIN_EMAIL || 'dev@orca.com',
      password,
      name: 'ORCA Studios',
    });
  }

  for (const digitalEmployee of digitalEmployees) await Worker.upsert(digitalEmployee);
  for (const permission of permissions) await WorkerPermission.upsert(permission);
  for (const connector of connectorDefinitions) await ConnectorDefinition.upsert(connector);
  for (const bundle of bundles) await WorkforceBundle.upsert(bundle);
  for (const membership of bundleMembers) await WorkforceBundleMember.upsert(membership);

  console.log('ORCA dynamic employee, team, department, and connector catalog seeded without deleting existing data.');
  await sequelize.close();
}

seed().catch(async (error) => {
  console.error('ORCA seed failed:', error);
  await sequelize.close();
  process.exit(1);
});
