const sequelize = require('./config/database');
const { Worker, WorkerPermission, User } = require('./models');
const bcrypt = require('bcrypt');

async function seed() {
  await sequelize.sync({ alter: true });

  const hashed = await bcrypt.hash('password123', 10);
  const [dev] = await User.findOrCreate({
    where: { id: '11111111-1111-1111-1111-111111111111' },
    defaults: {
      email: 'dev@orca.com',
      password: hashed,
      name: 'ORCA Studios',
    },
  });

  const digitalEmployees = [
    {
      id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
      name: 'Customer Service Specialist',
      developer_id: dev.id,
      description: 'Handles customer email, live chat, support tickets, returns, common account issues, and escalation preparation while following your approved policies and brand voice.',
      category: 'support',
      icon_url: '🎧',
      avg_rating: 0,
      total_reviews: 0,
      total_deployments: 0,
      price_model: 'subscription',
      base_price: 1795.00,
      comparable_monthly_salary: 3564.50,
      activation_fee: 2500.00,
      publisher_name: 'ORCA Studios',
      publisher_type: 'first_party',
      is_verified: true,
      is_orca_certified: true,
      product_type: 'individual',
      evidence_status: 'new',
      included_workload: 'Up to 750 resolved customer conversations per month across two approved channels.',
      supported_channels: ['Email', 'Live chat', 'Helpdesk'],
      supported_systems: ['Gmail', 'Slack', 'Zendesk', 'HubSpot'],
      integrations_included: 2,
      execution_limits: 'One production workspace and customer-approved policies. Higher volume is billed separately.',
      availability: '24/7 monitoring with customer-defined response and escalation windows.',
      support_level: 'Guided onboarding and monthly performance optimization.',
      protect_level: 'ORCA Protect Standard',
      overage_pricing: 'Quoted by channel, workload, and required response time.',
      evaluation_options: ['Sample Work', 'Complaint Resolution Test', 'Ticket Classification Test', 'Brand-Tone Test'],
      team_roles: [],
      version: '3.0.0',
      release_notes: 'Premium pricing, evaluation evidence, workload limits, and governed deployment metadata.',
      status: 'published',
    },
    {
      id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
      name: 'Digital Receptionist',
      developer_id: dev.id,
      description: 'Answers inbound inquiries, captures messages and leads, schedules appointments, routes requests, and follows approved escalation procedures.',
      category: 'admin',
      icon_url: '☎️',
      avg_rating: 0,
      total_reviews: 0,
      total_deployments: 0,
      price_model: 'subscription',
      base_price: 1495.00,
      comparable_monthly_salary: null,
      activation_fee: 2000.00,
      publisher_name: 'ORCA Studios',
      publisher_type: 'first_party',
      is_verified: true,
      is_orca_certified: true,
      product_type: 'individual',
      evidence_status: 'new',
      included_workload: 'Up to 500 inbound interactions and appointment actions per month.',
      supported_channels: ['Phone', 'Email', 'Calendar'],
      supported_systems: ['Google Calendar', 'Gmail', 'HubSpot', 'Slack'],
      integrations_included: 2,
      execution_limits: 'One business line, one primary calendar, and approved routing rules.',
      availability: '24/7 intake with customer-defined live-service and callback windows.',
      support_level: 'Guided onboarding and monthly routing optimization.',
      protect_level: 'ORCA Protect Standard',
      overage_pricing: 'Quoted by call volume, telephony cost, and workflow complexity.',
      evaluation_options: ['Sample Work', 'Reception Scenario Test', 'Scheduling Test', 'Lead Qualification Test'],
      team_roles: [],
      version: '2.0.0',
      release_notes: 'Repositioned as a premium digital receptionist with defined allowances and evaluation options.',
      status: 'published',
    },
    {
      id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
      name: 'E-commerce Support Specialist',
      developer_id: dev.id,
      description: 'Supports shoppers with product questions, order updates, returns, refunds, and approved Shopify customer-service workflows.',
      category: 'support',
      icon_url: '🛍️',
      avg_rating: 0,
      total_reviews: 0,
      total_deployments: 0,
      price_model: 'subscription',
      base_price: 1895.00,
      comparable_monthly_salary: null,
      activation_fee: 2750.00,
      publisher_name: 'ORCA Studios',
      publisher_type: 'first_party',
      is_verified: true,
      is_orca_certified: true,
      product_type: 'individual',
      evidence_status: 'new',
      included_workload: 'Up to 900 shopper conversations and order-support actions per month.',
      supported_channels: ['Email', 'Live chat', 'Store inbox'],
      supported_systems: ['Shopify', 'Gmail', 'Slack', 'HubSpot'],
      integrations_included: 2,
      execution_limits: 'One storefront and customer-approved refund, return, and escalation policies.',
      availability: '24/7 monitoring with customer-defined response windows.',
      support_level: 'Guided onboarding and monthly commerce workflow optimization.',
      protect_level: 'ORCA Protect Standard',
      overage_pricing: 'Quoted by interaction volume and order-operation complexity.',
      evaluation_options: ['Sample Work', 'Order Issue Test', 'Refund Policy Test', 'Escalation Judgment Test'],
      team_roles: [],
      version: '4.0.0',
      release_notes: 'Added premium commerce positioning, explicit workload limits, and evaluation evidence.',
      status: 'published',
    },
    {
      id: 'dddddddd-dddd-dddd-dddd-dddddddddddd',
      name: 'Sales Follow-Up Specialist',
      developer_id: dev.id,
      description: 'Follows up with qualified leads, maintains approved nurture sequences, records outcomes, and schedules sales conversations.',
      category: 'sales',
      icon_url: '📞',
      avg_rating: 0,
      total_reviews: 0,
      total_deployments: 0,
      price_model: 'subscription',
      base_price: 1995.00,
      comparable_monthly_salary: null,
      activation_fee: 3000.00,
      publisher_name: 'ORCA Studios',
      publisher_type: 'first_party',
      is_verified: true,
      is_orca_certified: true,
      product_type: 'individual',
      evidence_status: 'new',
      included_workload: 'Up to 1,000 approved follow-up actions per month across two channels.',
      supported_channels: ['Email', 'CRM', 'Calendar'],
      supported_systems: ['HubSpot', 'Gmail', 'Google Calendar', 'Slack'],
      integrations_included: 2,
      execution_limits: 'Customer-approved leads, messaging, cadence, and booking rules only.',
      availability: 'Continuous queue monitoring with customer-defined contact windows.',
      support_level: 'Guided onboarding and monthly conversion-workflow optimization.',
      protect_level: 'ORCA Protect Standard',
      overage_pricing: 'Quoted by contact volume, channel, and sequence complexity.',
      evaluation_options: ['Sample Work', 'Lead Follow-Up Test', 'Objection Handling Test', 'Calendar Booking Test'],
      team_roles: [],
      version: '2.0.0',
      release_notes: 'Premium sales workflow positioning with bounded scope and evaluation options.',
      status: 'published',
    },
    {
      id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
      name: 'YouTube Production Team',
      developer_id: dev.id,
      description: 'A coordinated multi-employee digital workforce for topic research, content planning, script development, and publishing preparation.',
      category: 'design',
      icon_url: '🎬',
      avg_rating: 0,
      total_reviews: 0,
      total_deployments: 0,
      price_model: 'subscription',
      base_price: 3995.00,
      comparable_monthly_salary: null,
      activation_fee: 5000.00,
      publisher_name: 'ORCA Studios',
      publisher_type: 'first_party',
      is_verified: true,
      is_orca_certified: true,
      product_type: 'team',
      evidence_status: 'new',
      included_workload: 'Up to four long-form content packages per month, each with research, plan, and draft script.',
      supported_channels: ['Content workspace', 'Email', 'Publishing handoff'],
      supported_systems: ['Notion', 'Google Drive', 'Slack', 'YouTube Studio'],
      integrations_included: 3,
      execution_limits: 'One channel brand, customer-approved sources, and one revision round per package.',
      availability: 'Continuous production queue with agreed delivery windows.',
      support_level: 'Guided onboarding, brand calibration, and monthly production review.',
      protect_level: 'ORCA Protect Standard',
      overage_pricing: 'Quoted per additional content package, revision, or specialized production step.',
      evaluation_options: ['Sample Work', 'Topic Research Test', 'Script Test', 'Brand Alignment Test'],
      team_roles: ['Research Specialist', 'Content Planner', 'Scriptwriter', 'Publishing Coordinator'],
      version: '3.0.0',
      release_notes: 'Reclassified as a premium multi-employee digital workforce with team roles and bounded output.',
      status: 'published',
    },
  ];

  for (const digitalEmployee of digitalEmployees) {
    await Worker.upsert(digitalEmployee);
  }

  const permissions = [
    { worker_id: digitalEmployees[0].id, tool: 'slack', scope: 'Read approved support messages', is_required: true },
    { worker_id: digitalEmployees[0].id, tool: 'slack', scope: 'Send approved support replies', is_required: true },
    { worker_id: digitalEmployees[1].id, tool: 'gmail', scope: 'Read approved reception inbox', is_required: true },
    { worker_id: digitalEmployees[1].id, tool: 'gmail', scope: 'Send approved reception messages', is_required: true },
    { worker_id: digitalEmployees[2].id, tool: 'shopify', scope: 'View approved order information', is_required: true },
    { worker_id: digitalEmployees[2].id, tool: 'shopify', scope: 'Perform approved order-support actions', is_required: false },
    { worker_id: digitalEmployees[3].id, tool: 'hubspot', scope: 'Read approved lead and contact records', is_required: true },
    { worker_id: digitalEmployees[4].id, tool: 'notion', scope: 'Read and write approved content workspace pages', is_required: true },
  ];

  for (const permission of permissions) {
    await WorkerPermission.findOrCreate({
      where: {
        worker_id: permission.worker_id,
        tool: permission.tool,
        scope: permission.scope,
      },
      defaults: permission,
    });
  }

  console.log('✅ ORCA digital employee catalog seeded without deleting existing data.');
  process.exit(0);
}

seed().catch((error) => {
  console.error('❌ ORCA catalog seed failed:', error);
  process.exit(1);
});
