const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const Worker = sequelize.define('Worker', {
  id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
  name: { type: DataTypes.STRING, allowNull: false },
  developer_id: { type: DataTypes.UUID, allowNull: false },
  developer_name: { type: DataTypes.STRING(160), allowNull: true },
  role_title: { type: DataTypes.STRING(180), allowNull: true },
  department: { type: DataTypes.STRING(160), allowNull: true },
  career_level: { type: DataTypes.STRING(100), allowNull: true },
  equivalent_experience_years: { type: DataTypes.INTEGER, allowNull: true },
  skills: { type: DataTypes.JSONB, allowNull: false, defaultValue: [] },
  work_modes: { type: DataTypes.JSONB, allowNull: false, defaultValue: ['support', 'coverage', 'role_fill'] },
  human_oversight: { type: DataTypes.TEXT, allowNull: true },
  support_summary: { type: DataTypes.TEXT, allowNull: true },
  regular_salary_annual: { type: DataTypes.DECIMAL(12, 2), allowNull: true },
  avatar_variant: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
  profile_image_url: { type: DataTypes.STRING, allowNull: true },
  readiness_state: { type: DataTypes.STRING(64), allowNull: false, defaultValue: 'defined' },
  verified_money_made: { type: DataTypes.DECIMAL(14, 2), allowNull: false, defaultValue: 0 },
  verified_money_saved: { type: DataTypes.DECIMAL(14, 2), allowNull: false, defaultValue: 0 },
  description: { type: DataTypes.TEXT },
  category: { type: DataTypes.ENUM('support','sales','admin','design','research'), allowNull: false },
  hero_banner_url: { type: DataTypes.STRING },
  icon_url: { type: DataTypes.STRING },
  avg_rating: { type: DataTypes.FLOAT, defaultValue: 0 },
  total_reviews: { type: DataTypes.INTEGER, defaultValue: 0 },
  total_deployments: { type: DataTypes.INTEGER, defaultValue: 0 },
  price_model: { type: DataTypes.ENUM('subscription','one_time','free'), defaultValue: 'free' },
  base_price: { type: DataTypes.DECIMAL(10,2), defaultValue: 0.00 },
  stripe_price_id: { type: DataTypes.STRING(255), allowNull: true },
  version: { type: DataTypes.STRING, defaultValue: '1.0.0' },
  release_notes: { type: DataTypes.TEXT },
  interview_prompt: { type: DataTypes.TEXT, allowNull: true },
  sample_prompt: { type: DataTypes.TEXT, allowNull: true },
  runtime_prompt: { type: DataTypes.TEXT, allowNull: true },
  status: { type: DataTypes.ENUM('draft','published','deprecated'), defaultValue: 'draft' },
  createdAt: DataTypes.DATE,
  updatedAt: DataTypes.DATE,
});

module.exports = Worker;
