const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const Worker = sequelize.define('Worker', {
  id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
  name: { type: DataTypes.STRING, allowNull: false },
  developer_id: { type: DataTypes.UUID, allowNull: false },
  description: { type: DataTypes.TEXT },
  category: { type: DataTypes.ENUM('support', 'sales', 'admin', 'design', 'research'), allowNull: false },
  hero_banner_url: { type: DataTypes.STRING },
  icon_url: { type: DataTypes.STRING },
  avg_rating: { type: DataTypes.FLOAT, defaultValue: 0 },
  total_reviews: { type: DataTypes.INTEGER, defaultValue: 0 },
  total_deployments: { type: DataTypes.INTEGER, defaultValue: 0 },
  price_model: { type: DataTypes.ENUM('subscription', 'one_time', 'free'), defaultValue: 'subscription' },
  base_price: { type: DataTypes.DECIMAL(10, 2), defaultValue: 0.00 },
  comparable_monthly_salary: { type: DataTypes.DECIMAL(10, 2), allowNull: true },
  activation_fee: { type: DataTypes.DECIMAL(10, 2), defaultValue: 0.00 },
  publisher_name: { type: DataTypes.STRING, defaultValue: 'ORCA Studios' },
  publisher_type: {
    type: DataTypes.STRING,
    defaultValue: 'first_party',
    validate: { isIn: [['first_party', 'third_party']] },
  },
  is_verified: { type: DataTypes.BOOLEAN, defaultValue: false },
  is_orca_certified: { type: DataTypes.BOOLEAN, defaultValue: false },
  product_type: {
    type: DataTypes.STRING,
    defaultValue: 'individual',
    validate: { isIn: [['individual', 'team']] },
  },
  evidence_status: {
    type: DataTypes.STRING,
    defaultValue: 'new',
    validate: { isIn: [['new', 'verified']] },
  },
  included_workload: { type: DataTypes.STRING },
  supported_channels: { type: DataTypes.JSONB, defaultValue: [] },
  supported_systems: { type: DataTypes.JSONB, defaultValue: [] },
  integrations_included: { type: DataTypes.INTEGER, defaultValue: 0 },
  execution_limits: { type: DataTypes.STRING },
  availability: { type: DataTypes.STRING },
  support_level: { type: DataTypes.STRING },
  protect_level: { type: DataTypes.STRING, defaultValue: 'ORCA Protect Standard' },
  overage_pricing: { type: DataTypes.STRING },
  evaluation_options: { type: DataTypes.JSONB, defaultValue: [] },
  team_roles: { type: DataTypes.JSONB, defaultValue: [] },
  version: { type: DataTypes.STRING, defaultValue: '1.0.0' },
  release_notes: { type: DataTypes.TEXT },
  status: { type: DataTypes.ENUM('draft', 'published', 'deprecated'), defaultValue: 'draft' },
  createdAt: DataTypes.DATE,
  updatedAt: DataTypes.DATE,
});

module.exports = Worker;
